# Generated by Django 4.1.3 on 2023-01-17 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("udyamHelper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="eventname",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="eventname",
            new_name="event",
        ),
    ]
