# Generated by Django 3.2.7 on 2023-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("udyamHelper", "0004_alter_event_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="teamname",
            field=models.CharField(max_length=50),
        ),
    ]
