# Generated by Django 3.2.7 on 2023-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0002_alter_useracount_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="useracount",
            name="radianite_points",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
