# Generated by Django 3.2.7 on 2022-12-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customauth", "0003_broadcast_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="useracount",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
