# Generated by Django 3.2.7 on 2023-01-27 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0003_useracount_radianite_points"),
        ("customauth", "0004_useracount_group"),
    ]

    operations = []
